drop table if exists members cascade;
drop table if exists teams cascade;

create table members
(
    id              bigint generated by default as identity,
    birthday        date                                              not null,
    work_start_date date                                              not null,
    name            varchar(20)                                       not null,
    role            varchar(10) check (role in ('MANAGER', 'MEMBER')) not null,
    team_name       varchar(20),
    primary key (id)
);

create table teams
(
    id      bigint generated by default as identity,
    manager varchar(20),
    name    varchar(20) not null unique,
    primary key (id)
);
